frontend/bots/urls.py
from django.conf.urls import url
from .views import (
    IndexView,
    ProcessTonebotView,
    CreateTonebotView,
    UpdateTonebotView,
    CreateFaqbotView,
    ProcessFaqbotView,
)

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create/tonebot$',  CreateTonebotView.as_view(), name='createtonebot'),
    url(r'^create/tonebot/(?P<botid>[\w-]+)$',  ProcessTonebotView.as_view(), name='processtonebot'),
    url(r'^update/tonebot/(?P<botid>[\w-]+)$',  UpdateTonebotView.as_view(), name='updatetonebot'),
    url(r'^create/faqbot$',  CreateFaqbotView.as_view(), name='createfaqbot'),
    url(r'^create/faqbot/(?P<botid>[\w-]+)$',  ProcessFaqbotView.as_view(), name='processfaqbot'),
    # url(r'^update/faqbot/(?P<botid>[\w-]+)$',  UpdateFaqbotView.as_view(), name='updatefaqbot'),
]

frontend/project/urls.py
from django.conf.urls.static import static
from django.conf import settings 
from django.conf.urls import url, include
from django.contrib import admin
# from sitemaps.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^bots/', include('bots.urls', namespace='bots')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^', include('sitemaps.urls', namespace='sitemaps')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/users/urls.py
from django.conf.urls import url
from .views import ProfileIndex, ToneSetting

urlpatterns = [
	url(r'^$',  ProfileIndex.as_view(), name='index'),
	url(r'^edit/(?P<option>[\w]+)$',  ToneSetting.as_view(), name='edit'),
]

frontend/users/models.py
from django.db import models
from django.dispatch import receiver
from allauth.account.signals import user_signed_up
from django.contrib.auth.models import User 

# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, related_name="profile")
	created = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return str(self.user)

	@receiver(user_signed_up, sender=User)
	def user_signed_up(request, user, *args, **kwargs):
		if user:
			profile = Profile.objects.get_or_create(user=user)

frontend/users/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
	class meta:
		model = Profile
		fields = []

frontend/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import Profile
from django.contrib.auth.models import User
from bots.models import Bot

class ProfileIndex(LoginRequiredMixin, View):
	template="users/index.html"
	def get(self, request):
		#filter by user/profile id
		all_bots = Bot.objects.all()
		print(len(all_bots))
		profile = get_object_or_404(Profile, user=request.user)
		context = {
			"profile": profile,
			"bots": all_bots,
		}
		return render(request, self.template, context)


class CreateTonebotView(View):
	template = 'bots/createtonebot.html'
	def get(self, request):
		return render(request, self.template)


class ProcessTonebotView(View):
	def get(self, request, botid):
	        	#if (request.user.is_authenticated()):
        		new_bot = Bot(
        			bot_id = botid,
        			profile = request.user.profile,
        			description = "new bot"
        		)
        		new_bot.save()
	        	return redirect("bots:index")

class UpdateTonebotView(View):
	template = 'bots/updatetonebot.html'
	def get(self, request, botid):
		context = {"botid": botid};
		return render(request, self.template, context)

class CreateFaqbotView(View):
	template = 'bots/createfaqbot.html'
	def get(self, request):
		return render(request, self.template)

class ProcessFaqbotView(View):
	def get(self, request, botid):
		if (request.user.is_authenticated()):
			pass

frontend/users/templates/users/createfaqbot.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}



 {% block content %}

 <div class="row">
 	<div class="col-xs-2 col-xs-offset-5 text-center">
 		<form method='POST' action=''>
            {% csrf_token %}

            <h3>Slack Token</h3>
            <input type=text class="slack-token">
            <hr>

            <h3>FAQ #1</h3>
            <div class="faqs">
                <div class="faq">
                    <label>Bot Response (answer):</label>
                    <input type="text" class="bot-response">
                    <div class="questions">
                        <label>Question Variations:</label>
                        <input type="text" class="question-variation">
                    </div>
                    <button class="add-variation btn btn-default">Add Question Variation</button>
                </div>
                <hr>
            </div>
            <button class="add-faq">Add another FAQ</button>
            <hr>


            <input type='submit' value='Create Bot!' class='add-bot-button btn btn-default' />
        </form>
 	</div>
 </div>
 <br />
 <br />

 </main>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
 <script>

    $(".faqs").on("click", ".add-variation", function(event){
        event.preventDefault();

        if($(this).parent().find(".questions input:last").val()){
            $(this).parent().find(".questions").append("<input class='question-variation' type='text'>");
        }
    });

    $(".add-faq").on("click", function(event){
        event.preventDefault();

        $(this).parent().find(".faqs").append(
            '<div class="faq"><label>Bot Response (answer):</label><input type="text" class="bot-response"><div class="questions"><label>Question Variations:</label><input type="text" class="question-variation"></div><button class="add-variation btn btn-default">Add Question Variation</button></div><hr>'
        );
    });


    var guid = function() {
        function s4() {
            return Math.floor((1 + Math.random()) * 0x10000)
                .toString(16)
                .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
    }

    $("form").submit(function(event){
        event.preventDefault();

        bot = {};
        bot["token"] = $("slack-token").val();
        bot["type"] = "faqbot";
        bot["properties"] = {};


        //build the response object
        $(".faq").each(function(){
            var uuid = guid();
            bot.properties[uuid] = {};
            bot.properties[uuid]["answer"] = $(this).find(".bot-response").val();
            bot.properties[uuid]["questions"] = [];

            $(this).find(".question-variation").each(function(){
                bot.properties[uuid]["questions"].push($(this).val());
            });
        });


        var data = {
            bot: bot
        };

        console.log(data);

        var jsonData = JSON.stringify(data);


        $.ajax({
            method: "POST",
            dataType: "json",
            contentType: "application/json",
            data: jsonData,
            url: "https://pacific-brushlands-11047.herokuapp.com/api/bots",
            success: function(response){
                createBotCallback(response);
            },
            error: function(jqxhr,textStatus,errorThrown) {
                console.log(textStatus + "; " + errorThrown);
            }
        });
    });

    function createBotCallback(response){
        var botID = response.bot_id;
        console.log(botID);
        window.location.href = botID;

        //redirect to create-bot url with botID as parameter
        //the creat-bot route will add new entry in the sqlite db
        //whch will redirect back to list of bots
    }

 </script>

 {% endblock content %}

frontend/users/templates/users/createtonebot.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}



 {% block content %}

 <div class="row">
 	<div class="col-xs-2 col-xs-offset-5 text-center">
 		<form method='POST' action=''>
            {% csrf_token %}

            <h3>Slack Token</h3>
            <input type=text class="slack-token">
            <hr>

            <h3>Anger</h3>
            <input type="range" class="anger-threshold" min="0" max="10">
            <div class="anger">
                <div class="anger-responses">
                    <input type="text" name="anger-1">
                </div>
                <input type="hidden" class="delimited-anger-responses">
                <button class="add-response btn btn-default">Add Response</button>
            </div>
            <hr>

            <h3>Joy</h3>
            <input type="range" class="joy-threshold" min="0" max="10">
            <div class="joy">
                <div class="joy-responses">
                    <input type="text" name="joy-1">
                </div>
                <input type="hidden" class="delimited-joy-responses">
                <button class="add-response btn btn-default">Add Response</button>
            </div>
            <hr>

            <h3>Sadness</h3>
            <input type="range" class="sadness-threshold" min="0" max="10">
            <div class="sadness">
                <div class="sadness-responses">
                    <input type="text" name="sadness-1">
                </div>
                <input type="hidden" class="delimited-sadness-responses">
                <button class="add-response btn btn-default">Add Response</button>
            </div>
            <hr>

            <h3>Fear</h3>
            <input type="range" class="fear-threshold" min="0" max="10">
            <div class="fear">
                <div class="fear-responses">
                    <input type="text" name="fear-1">
                </div>
                <input type="hidden" class="delimited-fear-responses">
                <button class="add-response btn btn-default">Add Response</button>
            </div>
            <hr>

            <h3>Disgust</h3>
            <input type="range" class="disgust-threshold" min="0" max="10">
            <div class="disgust">
                <div class="disgust-responses">
                    <input type="text" name="disgust-1">
                </div>
                <input type="hidden" class="delimited-disgust-responses">
                <button class="add-response btn btn-default">Add Response</button>
            </div>
            <hr>

            <input type='submit' value='Create Bot!' class='add-bot-button btn btn-default' />
        </form>
 	</div>
 </div>
 <br />
 <br />

 </main>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
 <script>

    var counter = 0;
    $(".add-response").on("click", function(event){
        event.preventDefault();


        if($(this).parent().find("div input:last").val()){
            counter++;
            var tone = $(this).parent().attr("class");
            $(this).parent().find("div").append("<input id='" + tone + counter + "' type='text'>");
        }
    });

    $("form").submit(function(event){
        event.preventDefault();

        var angerResponses = [];
        $(".anger-responses input").each(function() {
            angerResponses[$(this).attr("name")] = $(this).val();
        });
        angerResponses = Object.keys(angerResponses).map(function (key) {return angerResponses[key]})

        var joyResponses = [];
        $(".joy-responses input").each(function() {
            joyResponses[$(this).attr("name")] = $(this).val();
        });
        joyResponses = Object.keys(joyResponses).map(function (key) {return joyResponses[key]})

        var fearResponses = [];
        $(".fear-responses input").each(function() {
            fearResponses[$(this).attr("name")] = $(this).val();
        });
        fearResponses = Object.keys(fearResponses).map(function (key) {return fearResponses[key]})

        var disgustResponses = [];
        $(".disgust-responses input").each(function() {
            disgustResponses[$(this).attr("name")] = $(this).val();
        });
        disgustResponses = Object.keys(disgustResponses).map(function (key) {return disgustResponses[key]})

        var sadnessResponses = [];
        $(".sadness-responses input").each(function() {
            sadnessResponses[$(this).attr("name")] = $(this).val();
        });
        sadnessResponses = Object.keys(sadnessResponses).map(function (key) {return sadnessResponses[key]})



        var angerThreshold = $(".anger-threshold").val() / 10.0;
        var disgustThreshold = $(".disgust-threshold").val() / 10.0;
        var fearThreshold = $(".fear-threshold").val() / 10.0;
        var sadnessThreshold = $(".sadness-threshold").val() / 10.0;
        var joyThreshold = $(".joy-threshold").val() / 10.0;

        var slackToken = $(".slack-token").val();


        var data = {
        bot: {
                properties: {
                  anger: {
                    threshold: angerThreshold,
                    responses: angerResponses
                  },
                  joy: {
                    threshold: joyThreshold,
                    responses: joyResponses
                  },
                  sadness: {
                    threshold: sadnessThreshold,
                    responses: sadnessResponses
                  },
                  disgust: {
                    threshold: disgustThreshold,
                    responses: disgustResponses
                  },
                  fear: {
                    threshold: fearThreshold,
                    responses: fearResponses
                  }
                },
                token: slackToken,
                type: "tonebot",
                service: "slack",
                active: true
              }
        };


        var jsonData = JSON.stringify(data);


        $.ajax({
            method: "POST",
            dataType: "json",
            contentType: "application/json",
            data: jsonData,
            url: "https://pacific-brushlands-11047.herokuapp.com/api/bots",
            success: function(response){
                createBotCallback(response);
            },
            error: function(jqxhr,textStatus,errorThrown) {
                console.log(textStatus + "; " + errorThrown);
            }
        });
    });

    function createBotCallback(response){
        var botID = response.bot_id;
        console.log(botID);
        window.location.href = "tonebot/" + botID;

        //redirect to create-bot url with botID as parameter
        //the creat-bot route will add new entry in the sqlite db
        //whch will redirect back to list of bots
    }

 </script>

 {% endblock content %}

frontend/users/templates/users/dashboard.html
<div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Bot Type</th>
                  <th>Created</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                </tr>
                
              </tbody>
            </table>
          </div>

frontend/users/templates/users/index.html
{% extends 'base.html' %}


 {% block content %}

<!-- 	<h1>Hann</h1>

<h3>{{ profile.created }}</h3>

<h3>{{ profile.slack_token }}</h3> -->

   
<main>
    <div class="jumbotron" style="background-color: white;" >
      <div class="container text-center">
        <h3> Hey {{ profile }}</h3>
        <p>Bots are taking over are you in r out </p>
  <p><a class="btn btn-primary btn-lg" href="#about" role="button">Register &raquo;</a></p>
      </div>
    </div>


    <div class="container-fluid" id="profile-container" style="background-color: #f3f5f7;">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li style="margin-bottom: 30px;" class="active"><a href="#">Edit Profile <span class="sr-only">(current)</span></a></li>
            <li style="background-color: red; color: white; border-bottom: 1px solid black;  box-sizing: border-box;"><a href="#">Add Bots</a></li>
             <h3 class="text-center">Tone Bot</h3>
            <li style="background-color: white; color: white; border-bottom: 1px solid black"><a href="#">Edit Tone Bot</a></li>
            <li style="background-color: white; color: white; border-bottom: 1px solid black"><a href="#">Joy Settings </a></li>
            <li style="background-color: white; color: white;"><a href="#">Anger Settings </a></li>
            <li style="background-color: white; color: white;"><a href="#">Sadness Settings </a></li>
            <li style="background-color: white; color: white;"><a href="#">Disgust Settings </a></li>
            <li style="background-color: white; color: white;"><a href="#">Fear Settings </a></li>
          </ul>

          <h3 class="text-center">Faq Bot</h3>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
          </ul>

          <h3 class="text-center">Culture Bot</h3>
          <ul class="nav nav-sidebar">
            <li><a href="">Cultue Settings</a></li>
            
          </ul>
        </div>
        <div class="col-sm-9  col-md-10  main">
          <h1 class="page-header">Dashboard</h1>


          {% include "bots/index.html" with bots=bots %}
        

        </div>

       <div class="well text-center" style="background-color: white;">
        <p>Get Started by choosing a option within the side bar</p>
      </div>
        </div>
      </div>
    </div>


</main>

{% include 'footer.html' %}


 {% endblock content %}

frontend/users/templates/users/list.html
{% extends 'index.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}



 {% block bot_forms %}

 <main>


 <div class="row">
 	<div class="col-xs-2 col-xs-offset-5 text-center">
 		<a class="btn btn-default" href="{% url 'bots:createtonebot' %}">Add New Tonebot</a>
		<a class="btn btn-default" href="{% url 'bots:createfaqbot' %}">Add New FAQbot</a>
		<hr>
        		<h3>All Bots:</h3>
 		{% for bot in bots %}
 			{{bot.bot_type}}
	 		{% if bot.bot_type == "tonebot" %}	

	 			<h3><a href="{% url 'bots:updatetonebot' botid=bot.bot_id %}">{{bot.bot_id}}</a></h3>
	 		{% else %}
	 			<h3><a href="{% url 'bots:updatetonebot' botid=bot.bot_id %}">{{bot.bot_id}}</a></h3>
	 		{% endif %}
		{% endfor %}
 	</div>
 </div>

 </main>

 {% endblock bot_forms %}

frontend/users/templates/users/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Sign Out</a></li>
          </ul>
        </div>
      </div>
    </nav>

frontend/users/templates/users/settings_edit.html
{% load crispy_forms_tags %} 

<div class="col-sm-9  col-md-10  main well">
          <h1 class="page-header text-center">
            Edit {{ option|capfirst }} Settings
          </h1> 
            {% if form %}
              <form method="POST" action=""> {% csrf_token %}
              {{ form|crispy }}
              <input type="submit" value="Submit" class="btn btn-default" />
              </form> 
            {% endif %}
          </div>
        </div>

frontend/users/templates/users/updatefaqbot.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}



 {% block content %}

 <div class="row">
 	<div class="col-xs-2 col-xs-offset-5 text-center">
 		<form method='POST' action=''>
            {% csrf_token %}

            <h3>Slack Token</h3>
            <input type=text class="slack-token">
            <hr>

            <h3>FAQ #1</h3>
            <div class="faqs">
                <div class="faq">
                    <label>Bot Response (answer):</label>
                    <input type="text" class="bot-response">
                    <div class="questions">
                        <label>Question Variations:</label>
                        <input type="text" class="question-variation">
                    </div>
                    <button class="add-variation btn btn-default">Add Question Variation</button>
                </div>
                <hr>
            </div>
            <button class="add-faq">Add another FAQ</button>
            <hr>


            <input type='submit' value='Create Bot!' class='add-bot-button btn btn-default' />
        </form>
 	</div>
 </div>
 <br />
 <br />

 </main>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
 <script>

    $(".faqs").on("click", ".add-variation", function(event){
        event.preventDefault();

        if($(this).parent().find(".questions input:last").val()){
            $(this).parent().find(".questions").append("<input class='question-variation' type='text'>");
        }
    });

    $(".add-faq").on("click", function(event){
        event.preventDefault();

        $(this).parent().find(".faqs").append(
            '<div class="faq"><label>Bot Response (answer):</label><input type="text" class="bot-response"><div class="questions"><label>Question Variations:</label><input type="text" class="question-variation"></div><button class="add-variation btn btn-default">Add Question Variation</button></div><hr>'
        );
    });


    var guid = function() {
        function s4() {
            return Math.floor((1 + Math.random()) * 0x10000)
                .toString(16)
                .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
    }

    $("form").submit(function(event){
        event.preventDefault();

        bot = {};
        bot["token"] = $("slack-token").val();
        bot["type"] = "faqbot";
        bot["properties"] = {};


        //build the response object
        $(".faq").each(function(){
            var uuid = guid();
            bot.properties[uuid] = {};
            bot.properties[uuid]["answer"] = $(this).find(".bot-response").val();
            bot.properties[uuid]["questions"] = [];

            $(this).find(".question-variation").each(function(){
                bot.properties[uuid]["questions"].push($(this).val());
            });
        });


        var data = {
            bot: bot
        };

        console.log(data);

        var jsonData = JSON.stringify(data);


        $.ajax({
            method: "POST",
            dataType: "json",
            contentType: "application/json",
            data: jsonData,
            url: "https://pacific-brushlands-11047.herokuapp.com/api/bots",
            success: function(response){
                createBotCallback(response);
            },
            error: function(jqxhr,textStatus,errorThrown) {
                console.log(textStatus + "; " + errorThrown);
            }
        });
    });

    function createBotCallback(response){
        var botID = response.bot_id;
        console.log(botID);
        alert("Bot Updated!");
        window.location.href = botID;

        //redirect to create-bot url with botID as parameter
        //the creat-bot route will add new entry in the sqlite db
        //whch will redirect back to list of bots
    }

 </script>

 {% endblock content %}

frontend/users/templates/users/updatetonebot.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}



 {% block content %}
 <main>
 <div class="row">
 	<div class="col-xs-2 col-xs-offset-5 text-center">
        <div class="botForm"></div>
 	</div>
 </div>
 <br />
 <br />
 </main>


 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.2.1/mustache.min.js"></script>
 <script>
    $.ajax({
        method: "GET",
        dataType: "json",
        contentType: "application/json",
        url: "https://pacific-brushlands-11047.herokuapp.com/api/bots/{{botid}}",
        success: function(response){
            generateForm(response);
        },
        error: function(jqxhr,textStatus,errorThrown) {
            console.log(textStatus + "; " + errorThrown);
        }
    });

    var generateForm = function(bot) {
        var angerThreshold = bot.properties.anger.threshold * 10;
        var fearThreshold = bot.properties.fear.threshold * 10;
        var joyThreshold = bot.properties.joy.threshold * 10;
        var disgustThreshold = bot.properties.disgust.threshold * 10;
        var sadnessThreshold = bot.properties.sadness.threshold * 10;

        var template = "<form method='POST' action=''>{% csrf_token %}{% verbatim %}{{#properties}}<h3>Anger</h3><input type='range' class='anger-threshold' min='0' max='10' value='" + angerThreshold + "'><div class='anger'><div class='anger-responses'>{{#anger.responses}}<input type='text' value='{{.}}'>{{/anger.responses}}</div><button class='add-response btn btn-default'>Add Response</button></div><hr><h3>joy</h3><input type='range' class='joy-threshold' min='0' max='10' value='" + joyThreshold + "'><div class='joy'><div class='joy-responses'>{{#joy.responses}}<input type='text' value='{{.}}'>{{/joy.responses}}</div><button class='add-response btn btn-default'>Add Response</button></div><hr><h3>fear</h3><input type='range' class='fear-threshold' min='0' max='10' value='" + fearThreshold + "'><div class='fear'><div class='fear-responses'>{{#fear.responses}}<input type='text' value='{{.}}'>{{/fear.responses}}</div><button class='add-response btn btn-default'>Add Response</button></div><hr><h3>sadness</h3><input type='range' class='sadness-threshold' min='0' max='10' value='" + sadnessThreshold + "'><div class='sadness'><div class='sadness-responses'>{{#sadness.responses}}<input type='text' value='{{.}}'>{{/sadness.responses}}</div><button class='add-response btn btn-default'>Add Response</button></div><hr><h3>disgust</h3><input type='range' class='disgust-threshold' min='0' max='10' value='" + disgustThreshold + "'><div class='disgust'><div class='disgust-responses'>{{#disgust.responses}}<input type='text' value='{{.}}'>{{/disgust.responses}}</div><button class='add-response btn btn-default'>Add Response</button></div></hr>{{/properties}}<hr><input type='submit' value='Update Bot!' class='add-bot-button btn btn-default' /></form>{% endverbatim %}";
        var html = Mustache.to_html(template, bot);
        $(".botForm").html(html);


        var counter = 0;
        $(".add-response").on("click", function(event){
            event.preventDefault();


            if($(this).parent().find("div input:last").val()){
                counter++;
                var tone = $(this).parent().attr("class");
                $(this).parent().find("div").append("<input type='text'>");
            }
        });

        $("form").submit(function(event){
            event.preventDefault();
            var angerResponses = [];

            var count = 0;
            $(".anger-responses input").each(function() {
                count++;
                angerResponses[$(this).attr("name")] = $(this).val();
            });
            angerResponses = Object.keys(angerResponses).map(function (key) {return angerResponses[key]})

            console.log($(".anger-responses input"));
            console.log(count);

            var joyResponses = [];
            $(".joy-responses input").each(function() {
                joyResponses[$(this).attr("name")] = $(this).val();
            });
            joyResponses = Object.keys(joyResponses).map(function (key) {return joyResponses[key]})

            var fearResponses = [];
            $(".fear-responses input").each(function() {
                fearResponses[$(this).attr("name")] = $(this).val();
            });
            fearResponses = Object.keys(fearResponses).map(function (key) {return fearResponses[key]})

            var disgustResponses = [];
            $(".disgust-responses input").each(function() {
                disgustResponses[$(this).attr("name")] = $(this).val();
            });
            disgustResponses = Object.keys(disgustResponses).map(function (key) {return disgustResponses[key]})

            var sadnessResponses = [];
            $(".sadness-responses input").each(function() {
                sadnessResponses[$(this).attr("name")] = $(this).val();
            });
            sadnessResponses = Object.keys(sadnessResponses).map(function (key) {return sadnessResponses[key]})



            var angerThreshold = $(".anger-threshold").val() / 10.0;
            var disgustThreshold = $(".disgust-threshold").val() / 10.0;
            var fearThreshold = $(".fear-threshold").val() / 10.0;
            var sadnessThreshold = $(".sadness-threshold").val() / 10.0;
            var joyThreshold = $(".joy-threshold").val() / 10.0;


            var data = {
                properties: {
                  anger: {
                    threshold: angerThreshold,
                    responses: angerResponses
                  },
                  joy: {
                    threshold: joyThreshold,
                    responses: joyResponses
                  },
                  sadness: {
                    threshold: sadnessThreshold,
                    responses: sadnessResponses
                  },
                  disgust: {
                    threshold: disgustThreshold,
                    responses: disgustResponses
                  },
                  fear: {
                    threshold: fearThreshold,
                    responses: fearResponses
                  }
                }
              };

            console.log(data);
            var jsonData = JSON.stringify(data);


            $.ajax({
                method: "POST",
                dataType: "json",
                contentType: "application/json",
                data: jsonData,
                url: "https://pacific-brushlands-11047.herokuapp.com/api/bots/{{botid}}",
                success: function(response){
                    createBotCallback(response);
                },
                error: function(jqxhr,textStatus,errorThrown) {
                    console.log(textStatus + "; " + errorThrown);
                }
            });
        });

        function createBotCallback(response){
           // window.location.href = "update/{{botid}}";
            console.log(response);
            alert("Bot Updated!");
            //redirect to create-bot url with botID as parameter
            //the creat-bot route will add new entry in the sqlite db
            //whch will redirect back to list of bots
        }
    }

 </script>

 {% endblock content %}