frontend/bots/urls.py
from django.conf.urls import url
from .views import (
    IndexView,
    ProcessTonebotView,
    CreateTonebotView,
    UpdateTonebotView,
    CreateFaqbotView,
    ProcessFaqbotView,
)

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^create/tonebot$',  CreateTonebotView.as_view(), name='createtonebot'),
    url(r'^create/tonebot/(?P<botid>[\w-]+)$',  ProcessTonebotView.as_view(), name='processtonebot'),
    url(r'^update/tonebot/(?P<botid>[\w-]+)$',  UpdateTonebotView.as_view(), name='updatetonebot'),
    url(r'^create/faqbot$',  CreateFaqbotView.as_view(), name='createfaqbot'),
    url(r'^create/faqbot/(?P<botid>[\w-]+)$',  ProcessFaqbotView.as_view(), name='processfaqbot'),
    # url(r'^update/faqbot/(?P<botid>[\w-]+)$',  UpdateFaqbotView.as_view(), name='updatefaqbot'),
]

frontend/project/urls.py
from django.conf.urls.static import static
from django.conf import settings 
from django.conf.urls import url, include
from django.contrib import admin
# from sitemaps.views import HomePage

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^bots/', include('bots.urls', namespace='bots')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^', include('sitemaps.urls', namespace='sitemaps')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}{% endblock %}  Bots</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">
     <link href="{%static 'css/animate.css' %}" rel="stylesheet">
     <link href="{%static 'css/home_page.css' %}" rel="stylesheet">
     <link href="{%static 'users/css/users_page.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  </head>

    <body data-spy="scroll" data-target="#home-navbar">
    {% block content %}
    {% endblock content %}


    {% block style %}
    {% endblock style %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.1.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>  
    <script src="{% static 'js/custom.js' %}"></script>  
  </body>
</html>

frontend/templates/footer.html
 <footer >
        <p class="text-center">&copy; 2016 Closers</p>
      </footer>

frontend/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}
   
{% include 'navbar.html' %}


<div id="home" class="jumbotron">
  <div class="container text-center jumbo-header animated fadeInDownBig">
    <h1 class="lead">The Closers</h1>
      <p>Bring Bots From Ivory Tower to Main Street </p>
    <!-- <p><a class="btn btn-primary btn-lg" href="#about" role="button">Register &raquo;</a></p> -->
  </div>
</div>


<main class="container-fluid">
  <div id="about"  class="row marketing-row">
    <h1 class="text-center" id="about-title">
      Easy To Use!  Get Started Today
    </h1>
    <hr>
    <div class="about-info">
        <div class="col-xs-4 text-center">
        <i class="fa fa-slack fa-5x"></i>
        <h2 class="text-center">Simple To Use</h2>
        <p class="text-center faq-text">
           In under 10mins you'll be setup and ready to go.
           Theres no coding involed all you need to know is how to read and write.
        </p>
        </div>
        <div class="col-xs-4 text-center">
        <i class="fa fa-users fa-5x"></i>
        <h2 >Efficent Tracking</h2>
        <p class="text-center faq-text">
          
        </p>
        </div>
        <div class="col-xs-4 text-center">
          <i class="fa fa-commenting fa-5x"></i>
          <h2 class="text-center">Secure Data</h2>
          <p class="text-center faq-text"> 
            We do do not store any of your chat data meaning we are not selling your data to the FBI or anyone else. Any information you provide is only avaliable to you.
          </p>
        </div>
      </div>
    </div>
    


  <div id="demo" class="row demo-row">
    <h1 class="text-center"> Quick Demo </h1>
    <hr>
      <div class="text-center">
        <img src="{% static '/static/img/demo.gif' %}" id="img-demo" class="img-responsive demo text-center">
      
    </div>
    <hr>
  </div>


  <div id="questions" class="row question-row">
    <h1 class="text-center"> Frequently Asked Questions ?</h1>
    <hr>
  <div id="faq">
  <div class="row faq-row-1">
      <div class="col-xs-6 col-lg-6">
      <h2 class="text-center lead">What is Slack?</h2>
      <p class="text-muted text-center faq-text">
        Slack is an instant messaging and collaboration system on steroids. Slack’s channels help you focus by enabling you to separate messages, discussions and notifications. Slack provides traditional instant messaging functionality for you to do so. <a href="https://slack.com/">Learn More about Slack.</a> 
      </p>      
    </div>

    <div class="col-xs-6 col-lg-6">
      <h2 class="text-center lead">Who is this built for?</h2>
      <p class="text-muted text-center faq-text">
        This Service is for businesses that would like to help enhance their human resource department. It is not meant to take anyone job  This Service is for businesses that would like to hel boost their human resource department.
      </p>      
    </div>
  </div>
  
 <div class="row faq-row-2">
   <div class="col-xs-6 col-lg-6">
      <h2 class="text-center lead">How do I install this?</h2>
      <p class="text-muted text-center faq-text">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia quisquam ratione suscipit perferendis dolorem esse in quas perspiciatis, aperiam recusandae itaque ab consectetur animi commodi consequuntur deserunt, expedita adipisci at!
    </p>      
    </div>

    <div class="col-xs-6 col-lg-6">
      <h2 class="text-center lead">Can I use this to find my potential spouse?</h2>
      <p class="text-muted text-center faq-text"> 
          Our bots are very friendly and will talk back to you but they do play hard to get in regards to building a intimate relationship.  
      </p>      
    </div>
 </div>
   
  </div>

    <div class="text-center col-xs-12 ">
      <a class="btn btn-primary btn-lg signup-button" href="" role="button">Sign Up</a>
    </div>
  </div>


  <div id="contact" class="row contacts-row">
    <h1 class="text-center"> Contact Us </h1>
    <hr>
    <div class="col-xs-12 text-center">
      <div class="col-xs-6  col-xs-offset-3">
        <h1 class="text-center">{{ title }}</h1>
          {% if contact_form %}
            <form method="POST" action=""> {% csrf_token %}
            {{ contact_form|crispy }}
            <input type="submit" value="Submit" class="btn btn-default" />
            </form> 
          {% endif %}
      </div>
    </div>
  </div>
</main>
      <hr>
{% include 'footer.html' %}
 {% endblock %}

frontend/templates/modal.html
modal.html

frontend/templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top" id="home-navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="#home">Closers</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        <li><a href="#about">About</a></li>
        <li><a href="#demo">Demo</a></li>
        <li><a href="#questions">Questions</a></li>
        <li><a href="#contact">Contact</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        {% if user.is_anonymous %}
        <li><a href="{% url 'account_login' %}">Login</a></li>
        <li><a href="{% url 'account_signup' %}" >Register</a></li>
        {% else%}
        <li><a href="{% url 'profile:index' %}">Profile</a></li>
        <li><a href="{% url 'account_logout' %}">Logout</a></li>
        {% endif %}
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

frontend/templates/navbar2.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      {% if user.is_anonymous %}
        <li><a href="#" data-toggle="modal" data-target="#myModal">Login</a></li>
        <li><a href="#" data-toggle="modal" data-target="#regModal">SignUp</a></li>
      {% else %}
       <li><a id="logout" href="#">Logout</a></li>
      {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div id='login-form' class="modal-body">
       {% include 'account/signup.html' %}
      </div>
    </div>
  </div>
</div>

<!-- <div class="modal fade" id="regModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title" id="myModalLabel">Register</h4>
      </div>

      <div id="register-form" class="modal-body">
        <form id='form-register' class='text-center' action='' method='POST'>
            {{ reg_form.as_p }}
            <input id='omg' type='submit' value='Create' method='POST'/>
        </form>
      </div>
    </div>
  </div>
</div> -->


{% endblock content %}